#!/usr/bin/env node
// Injects (or refreshes) the OG/social meta block in every page that owns its <head>.
// Idempotent: replaces anything between the og:begin/og:end markers on re-run.
// AFTER THE DOMAIN SWAP: change SITE below and re-run `node tools/add-og.mjs`.
import fs from 'node:fs';
import path from 'node:path';

const SITE = 'https://monuments-2-0.vercel.app';
const IMG = `${SITE}/og/card.jpg`;

const DESCS = {
  '/':             'The creative portfolio of DJ Ramirez. Creative Director. Integrated campaigns, film, stills, experiential. LA / Boise.',
  '/work':         'Selected work. Campaigns across film, stills, and experiential.',
  '/about':        'Less agency, more rock and roll. The story, the crew, and the receipts.',
  '/capabilities': 'What I do, what I refuse to fake, and the crew behind it.',
  '/contact':      'Tell me what you’re building. LA / Boise.',
  '/photography':  'The photo archive. A decade of frames from sets and streets.',
  '/ai':           'AI is a tool, not a solution. Tools don’t buy taste.',
  '/giving':       'Some stories are not for sale.',
  '/hire':         'DJ Ramirez. Creative Director. Open to senior creative roles.',
  '/template':     'The Kit. The element library behind the site.',
};
const CASE_DESC = 'Case study from the creative portfolio of DJ Ramirez, Creative Director.';

function walk(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap(d => {
    const p = path.join(dir, d.name);
    return d.isDirectory() ? walk(p) : p.endsWith('.astro') ? [p] : [];
  });
}

const esc = s => s.replace(/&/g, '&amp;').replace(/"/g, '&quot;');
let touched = 0, skipped = [];

for (const file of walk('src/pages')) {
  let src = fs.readFileSync(file, 'utf8');
  if (!src.includes('<head>')) { continue; }                 // uses Base.astro
  if (file.includes('[')) { skipped.push(file); continue; }  // dynamic route
  const t = src.match(/<title>([\s\S]*?)<\/title>/);
  if (!t) { skipped.push(file); continue; }
  const title = t[1].trim().replace(/\s+/g, ' ');

  let route = '/' + path.relative('src/pages', file).replace(/\.astro$/, '');
  route = route.replace(/\/index$/, '') || '/';
  const url = route === '/' ? SITE + '/' : SITE + route;
  const desc = DESCS[route] ?? CASE_DESC;

  const block = [
    '  <!-- og:begin · generated by tools/add-og.mjs · re-run after domain swap -->',
    `  <meta name="description" content="${esc(desc)}">`,
    `  <link rel="canonical" href="${url}">`,
    '  <meta property="og:type" content="website">',
    '  <meta property="og:site_name" content="Monuments">',
    `  <meta property="og:title" content="${esc(title)}">`,
    `  <meta property="og:description" content="${esc(desc)}">`,
    `  <meta property="og:url" content="${url}">`,
    `  <meta property="og:image" content="${IMG}">`,
    '  <meta property="og:image:width" content="1200">',
    '  <meta property="og:image:height" content="630">',
    '  <meta name="twitter:card" content="summary_large_image">',
    `  <meta name="twitter:image" content="${IMG}">`,
    '  <!-- og:end -->',
  ].join('\n');

  // strip any previous block, then insert right after the <title> line
  src = src.replace(/[ \t]*<!-- og:begin[\s\S]*?<!-- og:end -->\n?/g, '');
  src = src.replace(/^([ \t]*<title>[\s\S]*?<\/title>)/m, `$1\n${block}`);
  fs.writeFileSync(file, src);
  touched++;
  console.log('og →', route, '·', title);
}
console.log(`\n${touched} pages stamped.`);
if (skipped.length) console.log('skipped (no title / dynamic):', skipped.join(', '));
