import { chromium } from 'playwright';
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const page = await ctx.newPage();
await page.addInitScript(() => localStorage.setItem('mnmt-accent','bw'));
await page.goto('http://localhost:4321/work/sony-xm5', { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(1500);
const brk = page.locator('.break').first();
await brk.scrollIntoViewIfNeeded();
await page.waitForTimeout(800);
const box = await brk.boundingBox();
await page.screenshot({ path: '/tmp/xm5-break.png', clip: { x: 0, y: box.y, width: 1440, height: box.height } });
await browser.close(); console.log('ok');
